### ISSUE TITLE
Does't work in AMD

### ISSUE THREAD

**Issue by alvaromuir** [Yuffster/Eve.js#18]
Can't get this work with RequireJS, but eve 0.2.3 does.
Any info?

**Comment by Yuffster** [comment]
Can you give me a code sample of things not working?  I'll load it up and dig around.

**Comment by alvaromuir** [comment]
Without me looking into it too much, I've found that eve 0.4.2 works with Raphael 2.1.0 in AMD (requireJS) but the current version wont..

Seems like there's something with it not attaching itself to window?

**Comment by Yuffster** [comment]
Eve.js is for scoped delegation metaframework for popular JavaScript libraries.  It wouldn't have any problem loading Raphael, for example, since the AMD support is baked into the way it loads YUI and Dojo, two frameworks it builds upon.

You're probably thinking of [eve](https://github.com/adobe-webplatform/eve), which is a cross-browser DOM events framework.
